language: php

sudo: false

php:
  - 7.1
  - 7.2
  - master

notifications:
  email: false

install:
  - composer install --dev

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml --testdox

after_success:
  - bash <(curl -s https://codecov.io/bash)
